version: '2'
services:
  web:
    build: .
    ports:
      -8000:80
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
db:
    image: myaql:5.5.49
    ports:
    - 3306:3306
    environmet:
    MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./myaql:ver/lib/myaql